name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - fix-website
    paths:
      - 'index.md'
      - 'page/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare pages directory
        run: |
          mkdir -p _site
          cp page/_config.yml _site/
          cp page/index.md _site/
          cp page/privacy_policy.md _site/
          cp page/terms_and_conditions.md _site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
